name: aml-wandb
channels:
- anaconda
dependencies:
- python==3.7.9
- pip==20.3.1
- pip:
  - torch==1.10.1
  - torchvision==0.11.2
  - pytorch-lightning==1.5.6
  - mlflow==1.22.0
  - azureml-mlflow==1.37.0
  - wandb==0.13.2
  - setuptools==59.5.0